services:
  AvvakumovOA-netology-prometheus:
    image: prom/prometheus:v2.47.2
    container_name: AvvakumovOA-netology-prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus
    ports:
      - "9090:9090"                 # внешний доступ с докер-сервера
    volumes:
      - /home/sysadmin/6-04-Docker-part2/6-04/prometheus:/etc/prometheus:ro  # конфиг из репо
      - prometheus-data:/prometheus           # данные TSDB
    networks:
      - AvvakumovOA-my-netology-hw
    restart: unless-stopped

  AvvakumovOA-netology-pushgateway:
    image: prom/pushgateway:v1.6.2
    container_name: AvvakumovOA-netology-pushgateway
    ports:
      - "9091:9091"                       # внешний доступ с докер-сервера
    networks:
      AvvakumovOA-my-netology-hw:
        aliases:
          - pushgateway                   
    restart: unless-stopped

volumes:
  prometheus-data:

networks:
  AvvakumovOA-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1